---@meta
-- ╔══════════════════════════════════════════════════════════════╗
-- ║  Annotations/KitnUI.lua — type-only definitions                ║
-- ║                                                                ║
-- ║  Loaded by wowlua-ls for editor autocomplete + nil-checking.   ║
-- ║  NOT loaded by WoW (not in the .toc). NOT shipped (stripped    ║
-- ║  from the zip by .pkgmeta's '- dev' entry; the folder IS       ║
-- ║  tracked in git). A living seed — extend, don't replace.       ║
-- ╚══════════════════════════════════════════════════════════════╝

-- The private addon namespace: the second value of `local _, ns = ...` in
-- every KitnUI file. Fields are attached across Core/Setup/Installer/Extras/
-- Wizard; add to this class as the LS flags a missing field.

---@class KitnUINS
---@field title string          # coloured "KitnUI:" print prefix
---@field profileName string    # profile name written into each addon's SV
---@field version string        # addon version (TOC metadata, "2.0" fallback)
---@field FONT string           # Expressway font path
---@field data table<string, any>   # per-addon profile payloads (Data/*.lua)
---@field db KitnUIDB               # SavedVariables (KitnUIDB)
---@field Wizard KitnUIWizard       # installer wizard singleton
---@field installerIsLoadMode boolean
---@field sessionExtras table<string, boolean>|nil
---@field Color fun(text: string): string
---@field Green fun(text: string): string
---@field Red fun(text: string): string
---@field Amber fun(text: string): string
---@field Ver fun(text: string): string
---@field ClassColor fun(text: string): string
---@field EUIReady fun(): boolean
---@field EUIProfile fun(folder: string): table|nil
---@field EUIStoredProfile fun(folder: string): table|nil   # the same profile read from EllesmereUI's saved variables, for a module that is switched off
---@field EUIAddon fun(folder: string): table|nil
---@field EUISettings fun(): table
---@field EUI_ABSENT string
---@field EUISnap fun(section: string, key: string): table|nil
---@field EUIPeekSnap fun(section: string, key: string): table|nil
---@field EUISnapGlobal fun(key: string): table|nil
---@field EUIPeekSnapGlobal fun(key: string): table|nil
---@field EUIOverride fun(tbl: table, saved: table, key: string, value: any)
---@field EUIRestore fun(tbl: table, saved: table, key: string)
---@field EUIRegisterReapply fun(fn: function)
---@field EUIQueueReapply fun()
---@field EUIResetAll fun(): boolean|nil
---@field EUI_DEFAULTS table       # EllesmereUI settings profile defaults (14 keys)
---@field EUISettingsDB fun(): table|nil   # EllesmereUI's db object for our settings, or nil
---@field KITN_PINK number[]
---@field BeginnerEnabled fun(): boolean
---@field NameplateArrowsEnabled fun(): boolean
---@field LuluEnabled fun(): boolean
---@field LuluLayoutName fun(): string
---@field LuluTearDown fun()
---@field LuluApplyActionBars fun(on: boolean)   # KitnUI_EUI only: the installer's module pass switches EllesmereUI's action bars through this so the change is per-character and recorded
---@field SetLuluMode fun(on: boolean)
---@field LuluReconcile fun()   # prompts to apply and reload when Lulu reads on but its action bar half is not in force
---@field EUI_INERT boolean      # KitnUI_EUI only: set by its Core.lua when KitnUI's shared namespace is unreachable, and every other file in that addon stops on it
---@field TopBar KitnUITopBar    # KitnUI_EUI only: the Top Bar module (KitnUI_EUI/TopBar/), reached through the EXPORTS bridge in KitnUI_EUI/Core.lua
---@field GetAddonDataVersion fun(addonKey: string): string?
---@field GetOutdatedAddons fun(): table[]
---@field IsAddonImported fun(addonKey: string): boolean
---@field SetupAddon fun(addonKey: string, import: boolean?, ...: any): boolean
---@field OpenInstaller fun(profileLoadMode: boolean?, updateKeys: table?, cdmMode: boolean?)
---@field GetInstallerData fun(self: KitnUINS, profileLoadMode: boolean?, updateKeys: table?, cdmMode: boolean?): table
---@field SnapshotProfiles fun()
---@field GetEUIModuleSet fun(): string[]
---@field ApplyEUIModuleSet fun()
---@field FinishInstallation fun()
---@field CleanMinimapIcons fun()
---@field RunCleanIcons fun(): boolean
---@field RunOptimize fun(): boolean
---@field RunChatSetup fun(): boolean
---@field IsAddOnAvailable fun(self: KitnUINS, addon: string): boolean
---@field IsCharLoaded fun(self: KitnUINS): boolean
---@field SetCharLoaded fun(self: KitnUINS)
local KitnUINS

-- SavedVariables shape (KitnUIDB). Written by Core.lua/Setup.lua on import.

---@class KitnUIDB
---@field profiles table<string, boolean|table>  # [addonKey] = true (CDM = per-spec table)
---@field addonVersions table<string, string>    # [addonKey] = X-header version at import
---@field extras table<string, boolean>          # [extraKey] = true once opted in; account-wide, replayed by /kitn load
---@field installedVersion string?
---@field perChar table<string, table>
---@field devMode boolean
---@field dismissedVersion string?
---@field euiSnap table<string, table>       # [section][profile][key] = { prev = <original> }, machine-local, never exported
---@field euiSnapGlobal table<string, table> # [key] = { prev = <original> } for values outside a profile: EllesmereUIDB-root settings, plus Lulu's two per-character debts, "luluEditModeLayout:<player GUID>" (preset index or layout name) and "luluActionBars:<player GUID>" (true where Lulu switched the module off)
---@field euiMigration number?               # version stamp for the one-time move of switch states into the profile
---@field euiSettings table?                 # vestigial pre-migration switch store, kept as evidence
local KitnUIDB

-- Installer wizard singleton (UI/Wizard.lua). Only the surface Installer.lua
-- calls is typed here; the frame + textures are Blizzard types.

---@class KitnUIWizard
---@field frame table
---@field page integer
---@field stepKeys table
---@field Build fun(self: KitnUIWizard): table?
---@field Queue fun(self: KitnUIWizard, data: table)
---@field SetPage fun(self: KitnUIWizard, n: integer)
---@field Show fun(self: KitnUIWizard)
---@field Hide fun(self: KitnUIWizard)
---@field SetOption fun(self: KitnUIWizard, i: integer, text: string, onClick: function)
---@field HideOptions fun(self: KitnUIWizard)
---@field FitOptions fun(self: KitnUIWizard, count: integer): number
---@field CenterOption1 fun(self: KitnUIWizard)
---@field StyleButton fun(self: KitnUIWizard, btn: table, text: string, fontSize: number?, onClick: function): any, any, any
---@field SetButtonVariant fun(self: KitnUIWizard, btn: table, variant: string)
---@field ShowStatusHeader fun(self: KitnUIWizard, text: string?)
---@field HideStatusHeader fun(self: KitnUIWizard)
---@field SetTitleIcon fun(self: KitnUIWizard, show: boolean?)
---@field SetOptionHint fun(self: KitnUIWizard, text: string)
local KitnUIWizard

-- Top Bar module (KitnUI_EUI/TopBar/: Bar.lua, Readouts.lua, Elements.lua).
-- KitnUI_EUI only, reached from KitnUI proper through the EXPORTS bridge in
-- KitnUI_EUI/Core.lua. No `self` parameter anywhere: unlike KitnUIWizard,
-- every member is called dot-style (ns.TopBar.Apply()), never with a colon.
-- Elements and ById are copied by reference at export time and only ever
-- appended to afterward, never reassigned.

---@class KitnUITopBar
---@field Get fun(key: string, fallback: any): any
---@field Set fun(key: string, v: any)
---@field Order fun(): table<string, table>   # { left = {...}, centre = {...}, right = {...} }, always populated
---@field SetOrder fun(left: table, centre: table, right: table)
---@field IsOff fun(id: string): boolean
---@field SetOff fun(id: string, v: boolean)
---@field RetryFit fun()
---@field ApplyVisibility fun()
---@field Apply fun()
---@field Enabled fun(): boolean
---@field SetEnabled fun(v: boolean)   # writes tbEnabled AND calls Apply() itself
---@field Frame fun(): table|nil       # the bar frame, nil until EnsureCreated builds it
---@field ResetPositions fun()
---@field Teardown fun()
---@field SizeClockButton fun()
---@field SuppressEUIFps fun(on: boolean)
---@field FriendsTooltip fun(tt: table)
---@field GuildTooltip fun(tt: table)
---@field VaultTooltip fun(tt: table)
---@field ApplyReadoutFonts fun()
---@field UpdateTicker fun()
---@field HearthValues fun(): table, table   # hearthValues, hearthOrder
---@field DEFAULT_ORDER table<string, string[]>   # { left = {...}, centre = {"clock"}, right = {...} }, read from ns.EUI_TB_DEFAULT_ORDER (Core.lua), the single source
---@field Elements table[]
---@field ById table<string, table>
---@field AccentRGB fun(): number, number, number   # r, g, b; Bar.lua's file-local, exported for Preview.lua's insert-line colour
---@field BuildPreviewHeader fun(parent: table, width: number): number   # the header height; the cold-mount builder EllesmereUI:SetContentHeader calls
---@field PreviewRefresh fun()   # rebuilds the preview's slot rows from current settings; a no-op unless the preview is mounted AND visible
---@field PreviewRestore fun()   # calls PreviewRefresh after an ordinary page revisit restores the cached header from _pageCache
local KitnUITopBar
